config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'tag/:name', to: 'events#tag', as: 'tag'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def tag
    if params.has_key?(:name)
      @events = Event.where(tag: params[:name])
      @tagTitle = params[:name]
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :imageURL, :description, :date, :tag, :latitude, :longitude)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_for(event, html: {class: 'form'}) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :imageURL, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :imageURL, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :date, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.datetime_select :date, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :latitude, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :latitude, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :longitude, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :longitude, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :tag, class: 'col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.select :tag, options_for_select(["University", "Local", "Music", "Educational", "Culture", "Food", "Family"]), {}, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-9" style="padding-top: 20px;">
      <%= f.submit 'Submit', class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h3>Editing Event</h3>

<div class='container'>
	<div class='row'>
		<div class='col-xs-12'>
			<%= render 'form', event: @event %>
		</div>
	</div>
	<div class='row'>
		<div class='col-xs-12'>
			<%= link_to 'Show', @event, class: 'btn-link' %> | <%= link_to 'Back', root_path, class: 'btn-link' %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Tag</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <%= image_tag(event.imageURL) %>
        <td><%= event.title %></td>
        <td><div><%= event.description %></div></td>
        <td><%= event.date %></td>
        <td><%= event.tag %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= link_to 'Show', event, class: 'btn-link' %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', root_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h3>New Event</h3>

<div class='container'>
	<div class='row'>
		<div class='col-xs-12'>
			<%= render 'form', event: @event %>
		</div>
	</div>
	<div class='row'>
		<div class='col-xs-12'>
			<%= link_to 'Back', root_path %>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <div class='row'>
    <div class='col-xs-12'>
      <h2><%= @event.title %></h2>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-6'>
      <strong>Description:</strong>
      <%= @event.description %>
    </div>
    <div class='col-xs-6'>
      <div class='row'>
        <div class='col-xs-12'>
          <%= image_tag(@event.imageURL) %>
        </div>
      </div>
      <div class='row'>
        <div class='col-xs-12'>
          <strong>Tag:</strong>
          <%= @event.tag %>
        </div>
      </div>
      <div class='row'>
        <div class='col-xs-12'>
          <strong>Date:</strong>
          <%= @event.date %>
        </div>
      </div>
      <div class='row'>
        <div class='col-xs-12'>
          <strong>Longitude:</strong>
          <%= @event.longitude %>
        </div>
      </div>
      <div class='row'>
        <div class='col-xs-12'>
          <strong>Latitude:</strong>
          <%= @event.latitude %>
        </div>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12'>
      <%= link_to 'Edit', edit_event_path(@event), class: 'btn-link' %> |
      <%= link_to 'Back', root_path, class: 'btn-link' %>
    </div>
  </div>
</div>

app/views/events/tag.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @tagTitle %> Events</h3>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Tag</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= image_tag(event.imageURL) %></td>
        <td><%= event.title %></td>
        <td><div><%= event.description %></div></td>
        <td><%= event.date %></td>
        <td><%= event.tag %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= link_to 'Show', event, class: 'btn-link' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: 'btn-link' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path, class: 'btn-link' %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h3>All Events</h3>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Tag</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= image_tag(event.imageURL) %></td>
        <td><%= event.title %></td>
        <td><div><%= event.description %></div></td>
        <td><%= event.date %></td>
        <td><%= event.tag %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= link_to 'Show', event, class: 'btn-link' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: 'btn-link' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: 'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialcal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/navigation' %>
  	<div id="main-container" class="container-fluid">
  		<div class="row">
  			<div class="col-xs-12">
    			<%= yield %>
    		</div>
    	</div>
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
	<a class="navbar-nav" style="padding-top: 10px;" href="/">
		<%= image_tag "icon.png", class: "d-inline-block align-top icon" %>
	</a>
	<a class="navbar-brand" href="/">
		SocialCal
	</a>
	<div class="navbar-nav">
		<%= link_to 'University', tag_path('University'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Local', tag_path('Local'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Music', tag_path('Music'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Educational', tag_path('Educational'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Culture', tag_path('Culture'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Food', tag_path('Food'), class: 'nav-item nav-link btn-link' %>
		<%= link_to 'Family', tag_path('Family'), class: 'nav-item nav-link btn-link' %>
	</div>
	</div>
</nav>